//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeFaltaUno.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MeFaltaUnoEntities : DbContext
    {
        public MeFaltaUnoEntities()
            : base("name=MeFaltaUnoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChatMessage> ChatMessage { get; set; }
        public virtual DbSet<ChatRoom> ChatRoom { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<Invitation> Invitation { get; set; }
        public virtual DbSet<InvitationStatus> InvitationStatus { get; set; }
        public virtual DbSet<Player> Player { get; set; }
        public virtual DbSet<RatePlayer> RatePlayer { get; set; }
        public virtual DbSet<RateStadium> RateStadium { get; set; }
        public virtual DbSet<Skill> Skill { get; set; }
        public virtual DbSet<Stadium> Stadium { get; set; }
        public virtual DbSet<State> State { get; set; }
        public virtual DbSet<Team> Team { get; set; }
        public virtual DbSet<TeamPlayer> TeamPlayer { get; set; }
    }
}
