//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeFaltaUno.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamPlayer
    {
        public int IdTeamPlayer { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual Team Team { get; set; }
    }
}
